version: '3.1'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lab_1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  spring-service:
    depends_on:
      - db
      - activemq
    image: user:latest
    ports:
      - "8080"
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/lab_1
      activemq.broker-url: tcp://activemq:61616
      spring.active-mq.user: admin
      spring.active-mq.password: admin
      spring.active-mq.queue: users

  process-spring-service-1:
    image: process:latest
    ports:
      - "8086:8082"
    restart: always
    depends_on:
      - spring-service
    environment:
      user-service-url: http://spring-service:8080
      service-port: 8086

  process-spring-service:
    image: process:latest
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - spring-service
    environment:
      user-service-url: http://spring-service:8080
      service-port: 8082

  process-spring-service-2:
    image: process:latest
    ports:
      - "8087:8082"
    restart: always
    depends_on:
      - spring-service
    environment:
      user-service-url: http://spring-service:8080
      service-port: 8087

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_WRITE_LOGIN: admin
      ACTIVEMQ_WRITE_PASSWORD: admin
      ACTIVEMQ_READ_LOGIN: admin
      ACTIVEMQ_READ_PASSWORD: admin
      ACTIVEMQ_JMX_LOGIN: admin
      ACTIVEMQ_JMX_PASSWORD: admin
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048